// 添加需要响应的消息类型, 存放一些不变量

export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM'; // 增加
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM'; // 减少
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const INCREMENT_TODO = 'INCREMENT_TODO'; // 增加
export type INCREMENT_TODO = typeof INCREMENT_TODO;

export const DECREMENT_TODO = 'DECREMENT_TODO'; // 减少
export type DECREMENT_TODO = typeof DECREMENT_TODO;

